services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/sonar
      SONAR_JDBC_USERNAME: pguser
      SONAR_JDBC_PASSWORD: pgpass
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_temp:/opt/sonarqube/temp
    networks:
      - sonarqube
    ports:
      - "9000:9000"

networks:
  sonarqube:
